name: Build FBNeo for Miyoo Mini Plus

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: miyoocft/miyoo-toolchain:v3.1.0
    steps:
    - name: Checkout Source Code
      uses: actions/checkout@v4
      with:
        repository: 'aleksei74/FBNeo'
        ref: 'master'

    - name: Compile Custom FBNeo Core
      run: |
        # 깃허브가 코드를 내려받은 절대 경로로 강제 이동 후 컴파일 실행
        cd ${{ github.workspace }}
        
        make -f Makefile.libretro platform=miyoo \
          CC=/opt/miyoo/usr/bin/arm-linux-gcc \
          CXX=/opt/miyoo/usr/bin/arm-linux-g++ \
          AR=/opt/miyoo/usr/bin/arm-linux-ar \
          WANT_NEOGEO=1 \
          HAVE_NEON=1 \
          CFLAGS="-O3 -marm -mtune=cortex-a7 -mfpu=neon-vfpv4 -mfloat-abi=hard" \
          CXXFLAGS="-O3 -marm -mtune=cortex-a7 -mfpu=neon-vfpv4 -mfloat-abi=hard"

    - name: Upload Finished Core (.so)
      uses: actions/upload-artifact@v4
      with:
        name: fbneo_libretro_miyoo
        path: ${{ github.workspace }}/fbneo_libretro.so
