name: Build FBNeo for Miyoo Mini Plus

on:
  workflow_dispatch: # 수동 가동 버튼 활성화

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Source Code
      uses: actions/checkout@v4
      with:
        repository: 'aleksei74/FBNeo'
        ref: 'master'

    - name: Install Compiler Toolchain
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential git crossbuild-essential-armhf

    - name: Compile Custom FBNeo Core
      run: |
        cd src/burn/libretro
        # 미유미니 컴파일러 수동 강제 매핑 및 세이부 축구 전용 슬림 빌드
        make -f Makefile.libretro platform=classic_armv7-a \
          CC=arm-linux-gnueabihf-gcc \
          CXX=arm-linux-gnueabihf-g++ \
          AR=arm-linux-gnueabihf-ar \
          HAVE_NEON=1 \
          EXCLUDE_DRIVERS=1 \
          INCLUDE_SEIBU=1 \
          CFLAGS="-O3 -march=armv7-a -mfpu=neon-vfpv4 -mfloat-abi=hard -fomit-frame-pointer -DOBJS_ONLY" \
          CXXFLAGS="-O3 -march=armv7-a -mfpu=neon-vfpv4 -mfloat-abi=hard -fomit-frame-pointer -DOBJS_ONLY"

    - name: Upload Finished Core (.so)
      uses: actions/upload-artifact@v4
      with:
        name: fbneo_libretro_miyoo
        path: src/burn/libretro/fbneo_libretro.so
